name: Release ServerStatus-go
on:
  push:
    tags:
      - v*
jobs:
  release:
    permissions: write-all
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ServerStatus-go ${{ github.ref }}
          draft: false
          prerelease: false
  linuxbuild:
    permissions: write-all
    name: build ServerStatus-go
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
    
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17
          
      - name: build linux version
        run: |
          go mod init client.go
          go mod tidy
          go build -o ServerStatus-go client.go
          
      - name: package
        run: tar -zcvf ServerStatus_go_linux.tgz ServerStatus-go status.ini serverstatus.service
        
      - name: upload
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: ServerStatus_go_linux.tgz
          asset_name: ServerStatus_go_linux.tgz
          asset_content_type: application/gzip

